CREATE TABLE comments (
  id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  content CLOB NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  board_id NUMBER,
  user_id NUMBER,
  CONSTRAINT fk_board FOREIGN KEY (board_id) REFERENCES boards (id) ON DELETE CASCADE,
  CONSTRAINT fk_user_comment FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
);